### PR TITLE
Add pyproject.toml and cleanup sdk installation

### PR DESCRIPTION
**Pull request by kannon92**
This PR adds `pyproject.toml` instead of setup.py.  The python community is moving to adopt pyproject.toml.  Another reason I moved to this is that the tool chain we use to generate the python code has an invalid setup.py.  

You can install our package like `python3 -m pip install sdk/python/.` with the `pyproject.toml` file.  

@danielvegamyhre this should fix your issue with /tmp and egg files.

### CODE REVIEW

**Comment by kannon92** [comment]
@ahg-g and @danielvegamyhre IMO we should maybe consider this as a patch release to 0.2.0.  0.2.0 package isn't capable of being installed as a package in a virtual environment.

**Comment by danielvegamyhre** [comment]
> @ahg-g and @danielvegamyhre IMO we should maybe consider this as a patch release to 0.2.0. 0.2.0 package isn't capable of being installed as a package in a virtual environment.

Agreed, we can include this in a v0.2.1 release. Thanks for putting this together!

**Comment by danielvegamyhre** [comment]
@kannon92 I was able to resolve the issue in my previous comment by updating the pyproject.toml per this stackoverflow post: https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout

Can we add this to the PR please?

**Comment by kannon92** [comment]
> Another issue: I have successfully installed the `jobset` package yet the create_jobset.py example script is unable to import it (I also tried importing it in a local python interpreter and it failed):
> 
> ```
> $ pip3 install .
> ...
> Successfully built jobset
> Installing collected packages: jobset
> Successfully installed jobset-0.2.0
> $ cd examples/
> $ ls
> create_jobset.py  README.md
> $ python3 create_jobset.py
> Traceback (most recent call last):
>   File "<redacted>/go/src/sigs.k8s.io/jobset/sdk/python/examples/create_jobset.py", line 5, in <module>
>     import jobset
> ModuleNotFoundError: No module named 'jobset'
> ```

I am unable to reproduce this actually.  

What version of python are you using?  And are you using a virtual environment or installing into system python?

**Comment by danielvegamyhre** [comment]
> > Another issue: I have successfully installed the `jobset` package yet the create_jobset.py example script is unable to import it (I also tried importing it in a local python interpreter and it failed):
> > ```
> > $ pip3 install .
> > ...
> > Successfully built jobset
> > Installing collected packages: jobset
> > Successfully installed jobset-0.2.0
> > $ cd examples/
> > $ ls
> > create_jobset.py  README.md
> > $ python3 create_jobset.py
> > Traceback (most recent call last):
> >   File "<redacted>/go/src/sigs.k8s.io/jobset/sdk/python/examples/create_jobset.py", line 5, in <module>
> >     import jobset
> > ModuleNotFoundError: No module named 'jobset'
> > ```
> 
> I am unable to reproduce this actually.
> 
> What version of python are you using? And are you using a virtual environment or installing into system python?

I am using a virtualenv with Python 3.11.2

**Comment by danielvegamyhre** [comment]
Interesting, I can import `jobset` from the `sdk/python` folder, but not from the `sdk/python/examples` folder.

I copied the `create_jobset.py` file from the examples folder to sdk/python and the import succeeds, but then the following error occurs on line 79 of the script:

```
...
list_namespaced_custom_object_with_http_info
    raise ApiTypeError(
kubernetes.client.exceptions.ApiTypeError: Got an unexpected keyword argument 'name' to method list_namespaced_custom_object
```

**Comment by danielvegamyhre** [comment]
I think i found a small bug in the script, I will submit a quick PR

**Comment by danielvegamyhre** [comment]
See #225 with the fix

**Comment by danielvegamyhre** [comment]
I notice in my venv site-packages, for every package besides jobset there is a pattern of 2 directories existing: `<package_name>` and `<package_name>-<version>.dist_info`. However, for jobset, there is only `jobset-0.2.0.dist_info`, but no `jobset`:

```

(venv) $ ~/go/src/sigs.k8s.io/jobset/sdk/python$ ls venv/lib/python3.11/site-packages/
cachetools                          iniconfig                    pyasn1_modules                   requests_oauthlib
cachetools-5.3.1.dist-info          iniconfig-2.0.0.dist-info    pyasn1_modules-0.3.0.dist-info   requests_oauthlib-1.3.1.dist-info
certifi                             jobset-0.2.0.dist-info       __pycache__                      rsa
certifi-2023.5.7.dist-info          kubernetes                   py.py                            rsa-4.9.dist-info
charset_normalizer                  kubernetes-26.1.0.dist-info  _pytest                          setuptools
charset_normalizer-3.1.0.dist-info  oauthlib                     pytest                           setuptools-66.1.1.dist-info
coverage                            oauthlib-3.2.2.dist-info     pytest-7.4.0.dist-info           six-1.16.0.dist-info
coverage-7.2.7.dist-info            packaging                    pytest_cov                       six.py
dateutil                            packaging-23.1.dist-info     pytest_cov-4.1.0.dist-info       urllib3
_distutils_hack                     pip                          pytest-cov.pth                   urllib3-1.26.16.dist-info
distutils-precedence.pth            pip-23.0.1.dist-info         pytest_randomly-1.2.3.dist-info  websocket
google                              pkg_resources                pytest_randomly.py               websocket_client-1.6.1.dist-info
google_auth-2.21.0.dist-info        pluggy                       python_dateutil-2.8.2.dist-info  _yaml
google_auth-2.21.0-py3.9-nspkg.pth  pluggy-1.2.0.dist-info       PyYAML-6.0.dist-info             yaml
idna                                pyasn1                       requests
idna-3.4.dist-info                  pyasn1-0.5.0.dist-info       requests-2.31.0.dist-info
```

**Comment by kannon92** [comment]
Can you try again?  I found a bug where I wasn't installing all the modules.

**Comment by danielvegamyhre** [comment]
@kannon92 Nice the import issue seems to be resolved

**Comment by danielvegamyhre** [comment]
/label tide/merge-method-squash
/lgtm
/approve

thanks for doing this! i'll patch this in to the last release as v0.2.1 and include #224 as well

**Pull request merged**
