### PR TITLE
docs: add argo workflow example for jobset

### PR DESCRIPTION
**Pull request by googs1025**
Since this PR https://github.com/kubernetes-sigs/jobset/pull/594 has been merged and we discussed it in the issue https://github.com/kubernetes-sigs/jobset/issues/545, it can now be integrated into argo-workflow. This PR provides some yaml examples for integrating argo workflow

### CODE REVIEW

**Comment by googs1025** [comment]
hi ! @shrinandj   maybe you could add more practical use cases

**Comment by danielvegamyhre** [comment]
This is great! Did you manually test the example and confirm it works as expected?

**Comment by googs1025** [comment]
> This is great! Did you manually test the example and confirm it works as expected?

yes, I use the local environment for testing.
we can see more detail : https://argo-workflows.readthedocs.io/en/latest/walk-through/kubernetes-resources/
as follows：
```bash

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl apply -f rbac.yaml
serviceaccount/argo-jobset unchanged
role.rbac.authorization.k8s.io/argo-jobset-role unchanged
rolebinding.rbac.authorization.k8s.io/argo-jobset-binding unchanged

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl create -f jobset.yaml
workflow.argoproj.io/argo-workflow-jobset-2bxrh created

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl get workflow -nargo
NAME                         STATUS    AGE   MESSAGE
argo-workflow-jobset-2bxrh   Running   8s

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl get pods -nargo
NAME                                   READY   STATUS    RESTARTS   AGE
argo-server-8577c7c558-lh6t7           1/1     Running   0          23h
argo-workflow-jobset-2bxrh             1/1     Running   0          18s
httpbin-6c989cbc8c-f86wr               1/1     Running   0          23h
minio-6b665ffb45-gq9n6                 1/1     Running   0          23h
paralleljobs-driver-0-0-s6ztn          1/1     Running   0          16s
paralleljobs-workers-0-0-95g48         1/1     Running   0          16s
paralleljobs-workers-0-1-vlcnq         1/1     Running   0          16s
paralleljobs-workers-0-2-b24kk         1/1     Running   0          16s
paralleljobs-workers-0-3-7qvhs         1/1     Running   0          16s
workflow-controller-76ffbdcf8f-vlwwc   1/1     Running   0          23h

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl get pods -nargo
NAME                                   READY   STATUS    RESTARTS   AGE
argo-server-8577c7c558-lh6t7           1/1     Running   0          23h
argo-workflow-jobset-2bxrh             1/1     Running   0          71s
httpbin-6c989cbc8c-f86wr               1/1     Running   0          23h
minio-6b665ffb45-gq9n6                 1/1     Running   0          23h
paralleljobs-driver-0-0-s6ztn          1/1     Running   0          69s
paralleljobs-workers-0-0-95g48         1/1     Running   0          69s
paralleljobs-workers-0-1-vlcnq         1/1     Running   0          69s
paralleljobs-workers-0-2-b24kk         1/1     Running   0          69s
paralleljobs-workers-0-3-7qvhs         1/1     Running   0          69s
workflow-controller-76ffbdcf8f-vlwwc   1/1     Running   0          23h

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl get jobset -nargo
NAME           TERMINALSTATE   RESTARTS   COMPLETED   SUSPENDED   AGE
paralleljobs                                                      99s

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl get jobset -nargo
NAME           TERMINALSTATE   RESTARTS   COMPLETED   SUSPENDED   AGE
paralleljobs   Completed                  True                    110s

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl get pods -nargo
NAME                                   READY   STATUS      RESTARTS   AGE
argo-server-8577c7c558-lh6t7           1/1     Running     0          23h
argo-workflow-jobset-2bxrh             0/1     Completed   0          116s
httpbin-6c989cbc8c-f86wr               1/1     Running     0          23h
minio-6b665ffb45-gq9n6                 1/1     Running     0          23h
paralleljobs-driver-0-0-s6ztn          0/1     Completed   0          114s
paralleljobs-workers-0-0-95g48         0/1     Completed   0          114s
paralleljobs-workers-0-1-vlcnq         0/1     Completed   0          114s
paralleljobs-workers-0-2-b24kk         0/1     Completed   0          114s
paralleljobs-workers-0-3-7qvhs         0/1     Completed   0          114s
workflow-controller-76ffbdcf8f-vlwwc   1/1     Running     0          23h

root@VM-0-3-ubuntu:/home/ubuntu/example# kubectl get workflow -nargo
NAME                         STATUS      AGE    MESSAGE
argo-workflow-jobset-2bxrh   Succeeded   2m7s
```

**Comment by danielvegamyhre** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
