### PR TITLE
Use jobset-system instead of kind-system for jobset

### LINKED ISSUE #356: JobSet logs are not displayed in our e2e tests
**What would you like to be added**:

We should have the jobset controller pods in our e2e tests. Currently, they are missing from the logs.

See https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/244/pull-jobset-test-e2e-main-1-29/1737240901450731520/artifacts/ and notice that jobset does not have any logs.

**Why is this needed**:
JobSet controller is critical for debugging issues and we should have the logs on the e2e test.

### PR DESCRIPTION
**Pull request by kannon92**
We are not finding the correct namespace so we have no logs.

Fixes #356

### CODE REVIEW

**Comment by danielvegamyhre** [comment]
Thanks for looking into this

/lgtm
/approve

**Comment by kannon92** [comment]
/hold

Want to confirm that it works before merge.

**Comment by kannon92** [comment]
Can confirm that this works: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/358/pull-jobset-test-e2e-main-1-28/1737556386608320512/artifacts/

You can browse there and see the logs.

/hold cancel

**Pull request merged**
