### PR TITLE
allow for podman to be used for running tests

### LINKED ISSUE #332: Allow for use of podman for running containers in development.
We migrated the generation of the python sdk code to use docker.  Currently, we require that docker must be enabled on host to build.  

Kubernetes/Kind actually allow the use of podman rather than docker.  

It would be ideal to allow for either Podman or Docker for running the test code.

```
kehannon@kehannon-thinkpadp1gen4i:~/Work/jobset$ make test
test -s /home/kehannon/Work/jobset/bin/controller-gen && /home/kehannon/Work/jobset/bin/controller-gen --version | grep -q v0.11.4 || \
GOBIN=/home/kehannon/Work/jobset/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.4
/home/kehannon/Work/jobset/bin/controller-gen \
        rbac:roleName=manager-role output:rbac:artifacts:config=config/components/rbac\
        crd:generateEmbeddedObjectMeta=true output:crd:artifacts:config=config/components/crd/bases\
        webhook output:webhook:artifacts:config=config/components/webhook\
        paths="./..."
go fmt ./...
go vet ./...
test -s /home/kehannon/Work/jobset/bin/setup-envtest || GOBIN=/home/kehannon/Work/jobset/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
echo "testing Python SDK..."
testing Python SDK...
./hack/python-sdk/test-sdk.sh
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
make: *** [Makefile:130: test-python-sdk] Error 1
```

### PR DESCRIPTION
**Pull request by kannon92**
Fixes #332 

This allows one to substitute podman over docker.

### CODE REVIEW

**Comment by kannon92** [comment]
@danielvegamyhre wdyt about this PR?

Podman has over 12k stars so it seems to be well used. On fedora, it is the default container engine so it would be nice to not require docker.

Kind also has some support for podman.

**Comment by danielvegamyhre** [comment]
Looks good to me! Did you manually test that the defaulting to docker works?

**Comment by kannon92** [comment]
> Looks good to me! Did you manually test that the defaulting to docker works?

Yea, I tested both cases.

**Comment by kannon92** [comment]
@danielvegamyhre when you get a chance, can you give a lgtm also?

**Pull request merged**
