### PR TITLE
Pass a context from controller to the IndexerFunc

### PR DESCRIPTION
**Pull request by tenzen-y**
I modified the func `SetupIndexes` to pass a context from the controller to the IndexerFunc.

### CODE REVIEW

**Comment by danielvegamyhre** [comment]
Is the purpose of this to have a shared context for contextual logging?

**Comment by tenzen-y** [comment]
> Is the purpose of this to have a shared context for contextual logging?

In general, I think we should pass a context generated in the parent to the child function instead of using an empty context (another parent context).

So, we can propagate canceling to the child.

**Comment by danielvegamyhre** [comment]
/lgtm

Will leave approval to Abdullah

**Comment by tenzen-y** [comment]
Rebased.

**Pull request merged**
