### PR TITLE
wip: Fix generation

### LINKED ISSUE #508: Issue generating manifests
I am unable to run `make generate`.

Using the latest main, my environment seems to be stuck on generating code.

```
kehannon@kehannon-thinkpadp1gen4i:~/Work/jobset$ pwd
/home/kehannon/Work/jobset
kehannon@kehannon-thinkpadp1gen4i:~/Work/jobset$ make generate
test -s /home/kehannon/Work/jobset/bin/controller-gen && /home/kehannon/Work/jobset/bin/controller-gen --version | grep -q v0.14.0 || \
GOBIN=/home/kehannon/Work/jobset/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0
cp -f /home/kehannon/.gobrew/current/go/bin/pkg/mod/k8s.io/code-generator@v0.29.3/generate-groups.sh /home/kehannon/Work/jobset/bin/
cp -f /home/kehannon/.gobrew/current/go/bin/pkg/mod/k8s.io/code-generator@v0.29.3/generate-internal-groups.sh /home/kehannon/Work/jobset/bin/
cp -f /home/kehannon/.gobrew/current/go/bin/pkg/mod/k8s.io/code-generator@v0.29.3/kube_codegen.sh /home/kehannon/Work/jobset/bin/
/home/kehannon/Work/jobset/bin/openapi-gen --go-header-file hack/boilerplate.go.txt -i sigs.k8s.io/jobset/api/jobset/v1alpha2 -p sigs.k8s.io/jobset/api/jobset/v1alpha2 --alsologtostderr
2024/04/12 15:11:11 OpenAPI code generation error: Failed making a parser: unable to add directory "sigs.k8s.io/jobset/api/jobset/v1alpha2": No files for pkg "sigs.k8s.io/jobset/api/jobset/v1alpha2"
make: *** [Makefile:243: openapi-gen] Error 1
```

Does anyone else have this problem?

I realize that I am not following best practices about making sure your code is in $GOPATH but that hasn't been an issue before.

### PR DESCRIPTION
**Pull request by kannon92**
Fixes #508

### CODE REVIEW

**Comment by danielvegamyhre** [comment]
I think this is an environment specific issue, I just cloned jobset into tmp/ and ran `make generate` and it worked. Last time I saw `make generate` failing it was due to a missing GOPATH.

**Comment by kannon92** [comment]
Yea I just don't understand why if I change v1alpha2 -> v1alpha1 or v1alpha2->v1beta1 it works without issue. 

My gopath is set (I use gobrew so it points to 1.22.2 version).

**Pull request closed without merging**
