### PR TITLE
update kind to 0.20.0

### PR DESCRIPTION
**Pull request by kannon92**
@dejanzele pointed out some issues with the setup and I can replicate it on latest version of kind.

Want to test it out in CI to verify my hypothesis.

### CODE REVIEW

**Comment by dejanzele** [comment]
I don't know can amd64 or arm64 build of kind impact this somehow. I have issues in `kind v0.20.0 go1.20.5 darwin/arm64` for sure. I'll try to validate on a linux amd64 machine.

**Comment by kannon92** [comment]
> I don't know can amd64 or arm64 build of kind impact this somehow. I have issues in `kind v0.20.0 go1.20.5 darwin/arm64` for sure. I'll try to validate on a linux amd64 machine.

So the e2e tests sometimes see this error and the deployment doesn’t come up. I will see about installing it on a real kube cluster.

I don’t know why the e2e tests sometimes work and sometimes fail horribly…

**Comment by danielvegamyhre** [comment]
> @dejanzele pointed out some issues with the setup and I can replicate it on latest version of kind.
> 
> Want to test it out in CI to verify my hypothesis.

@kannon92 is this PR for testing purposes only? If so, let's mark it with a hold label.

**Comment by kannon92** [comment]
/hold cancel

I put a hold on this because I wanted to see if this would cause more flakes or not. Didn't see that.

**Pull request merged**
