### PR TITLE
drop job-name from labels as it is not used

### LINKED ISSUE #26: Headless service should use fully qualified job label name.
https://github.com/kubernetes-sigs/jobset/blob/main/pkg/controllers/jobset_controller.go#L244

```
					// TODO: Migrate to the fully qualified label name.
					"job-name": job.Name,
```

Generally, we should use names that are fully qualified for labels.

Not sure if that means we should reject JobSpec names that aren't valid label names.

### PR DESCRIPTION
**Pull request by kannon92**
#### What this PR does / why we need it:
Drop use of legacy label. It seems that this was no longer used.
#### Which issue(s) this PR fixes:

Fixes #26 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by kannon92** [comment]
/hold

https://github.com/kubernetes-sigs/jobset/pull/640 is introducing usage of this so it may be used.

**Comment by danielvegamyhre** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
