### PR TITLE
boiler plate code for kep templating

### PR DESCRIPTION
**Pull request by kannon92**
Add some boiler plate code for KEP updates and verfies.

### CODE REVIEW

**Comment by kannon92** [comment]
@danielvegamyhre I goofed on adding KEPs to jobset and I missed a few items.  I have this in the other PR but I think its worth moving out and having this go in separately.

**Comment by danielvegamyhre** [comment]
@kannon92 have you manually tested this additional bash script?

**Comment by kannon92** [comment]
> @kannon92 have you manually tested this additional bash script?

Yea, in https://github.com/kubernetes-sigs/jobset/pull/244, I used it to update the toc for my KEP and I have it added in `Makefile` as part of the verify step to make sure the toc matches.

**Pull request merged**
