### PR TITLE
update golang to 1.22

### PR DESCRIPTION
**Pull request by kannon92**
Seems like a lot of kube dependencies are upgrading to 1.22 with kube 1.30 coming down the pipe.

Let's bump this to 1.22. We just bumped our CI to run with 1.22 image.

### CODE REVIEW

**Comment by kannon92** [comment]
hmm. maybe we can't do this yet.

**Comment by kannon92** [comment]
/hold

Something is not right here.

**Comment by danielvegamyhre** [comment]
> /hold
> 
> Something is not right here.

`1.593 sigs.k8s.io/jobset/pkg/util/collections: cannot compile Go 1.22 code`

Did you run `go mod tidy` after bumping the go version

**Comment by kannon92** [comment]
yea I wonder if the test-infra image is using 1.21.0.

**Comment by kannon92** [comment]
I have https://github.com/kubernetes/test-infra/pull/32302 to see if that will fix the PR.

**Comment by kannon92** [comment]
Opened up https://github.com/kubernetes-sigs/kueue/pull/1895 to see.

This seems to work so please review https://github.com/kubernetes/test-infra/pull/32302 when you get a chance.

**Comment by kannon92** [comment]
/hold cancel

Found out that kueue parametrizes BUILDER_IMAGE

**Pull request merged**
