### PR TITLE
add dependabot

### LINKED ISSUE #13: Automate dependencies update
Can be done using dependabot https://github.com/kubernetes-sigs/kueue/issues/435

### PR DESCRIPTION
**Pull request by kannon92**
Fixes #13 

Add dependabot and follow same configuration as Kueue.

### CODE REVIEW

**Comment by ahg-g** [comment]
Thanks Kevin, can you pls explain a bit what will that do? which dependencies will be updated and how the update will be triggered?

**Comment by kannon92** [comment]
So this is the exact same config that we are using in Kueue for updating dependencies.  

```
version: 2
updates:

  # Maintain dependencies for go
  - package-ecosystem: "gomod" // Look at gomodules
    directory: "/"
    schedule:
      interval: "weekly" // Check on a weekly cadence and see if anything needs an update
    labels:
      - "ok-to-test" // Adds the "ok-to-test" label to every PR
    ignore:
      # Ignore major and minor versions for dependencies updates
      # Allow patches and security updates.
// Generally only update major.minor upgrades for K8 dependencies.
      - dependency-name: k8s.io/*
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
```

I figured the Kueue config you all are happy with as I don't believe it has changed much since I added it.

**Pull request merged**
