### PR TITLE
add jobset docsite

### PR DESCRIPTION
**Pull request by moficodes**
Part of #401

### CODE REVIEW

**Comment by ahg-g** [comment]
/retest

Thanks Mofi, how can we view this?

**Comment by moficodes** [comment]
Until netlify is setup only way would be to view locally.

I have a isssue in kubernetes orgs for netlify access. https://github.com/kubernetes/org/issues/4748

If you want to run locally steps would

* Install Hugo
* `cd site`
* `npm install`
* `hugo server`

**Comment by ahg-g** [comment]
/lgtm
/approve

Thanks!

**Comment by danielvegamyhre** [comment]
This is great, thank you!

**Pull request merged**
