### PR TITLE
Relax validation on enableDNSHostnames

### LINKED ISSUE #138: Allow setting enableDNSHostnames for non-indexed jobs
**What would you like to be added**:

Allow setting enableDNSHostnames for non-indexed jobs

**Why is this needed**:

See discussion https://github.com/kubernetes-sigs/jobset/issues/132#issuecomment-1543348063

### PR DESCRIPTION
**Pull request by danielvegamyhre**
Fixes #138

### CODE REVIEW

**Comment by danielvegamyhre** [comment]
> I think there were a few test cases in jobset_controller_test.go that we should also remove.
> 
> https://github.com/kubernetes-sigs/jobset/blob/main/test/integration/controller/jobset_controller_test.go#L123

Am I crazy or does this test case not do what the test description says it does? If so, how did this happen...?

**Comment by kannon92** [comment]
Github blame says it was me!  https://github.com/kubernetes-sigs/jobset/pull/20

**Comment by kannon92** [comment]
Let me know how you want to handle this test case.

> The jobset is created with a job in NonIndexed completion mode and EnableDNSHostnames=true, but it is configured to expected the jobset creation to succeed.

I don't think we ever do the validation in the jobset code as it is enforced for webhooks.  With this PR I think you'd want to remove this test case anyway as we now allow `enableDNSHostnames` for both.

**Comment by danielvegamyhre** [comment]
> Github blame says it was me! #20

No worries! I am un-merging the test cases in this PR.

**Review by kannon92 — APPROVED** [review]
lgtm

**Pull request merged**
