### PR TITLE
chore: use symbolic link instead of directory

### PR DESCRIPTION
**Pull request by googs1025**
- use symbolic link instead of directory to avoid examples inconsistencies

### CODE REVIEW

**Comment by googs1025** [comment]
/hold 
When both PR https://github.com/kubernetes-sigs/jobset/pull/601 and PR https://github.com/kubernetes-sigs/jobset/pull/629 are merged, I will rebase again

**Comment by googs1025** [comment]
Same as kueue project: https://github.com/kubernetes-sigs/kueue/blob/main/examples

**Comment by danielvegamyhre** [comment]
Seems like this needs a rebase @googs1025

**Comment by googs1025** [comment]
After this PR  https://github.com/kubernetes-sigs/jobset/pull/601 is merged, I will rebase it together

**Comment by danielvegamyhre** [comment]
@googs1025 are you still working on this?

**Comment by googs1025** [comment]
> @googs1025 are you still working on this?

Yes, but I want to wait until the PR https://github.com/kubernetes-sigs/jobset/pull/601 is merged before making the changes. This will prevent the PR https://github.com/kubernetes-sigs/jobset/pull/601 from needing to be rebased.

**Comment by googs1025** [comment]
Already ready for next !

**Comment by danielvegamyhre** [comment]
@googs1025 why did you delete some of the examples, is that an accident? You may need to rebase

**Comment by googs1025** [comment]
main: https://github.com/kubernetes-sigs/jobset/tree/main/site/static/examples 
https://github.com/googs1025/jobset/tree/remove-example/site/static/examples

I checked and found that site/static/examples already has these examples. So those in examples/ can be deleted directly.
This way we don’t have to maintain two sets of examples, which can easily increase example inconsistencies.

**Comment by googs1025** [comment]
@danielvegamyhre

**Pull request merged**
